#!/bin/sh

MINENAME=legumemine
DBNAME=legumemine-dev

## add triggers
./gradlew generateUpdateTriggers
psql $DBNAME -f dbmodel/build/resources/main/add-update-triggers.sql

## do updates
cd ~/java/ncgr/intermine
echo "########## cdsreferenceupdater ${MINENAME}"
./cdsreferenceupdater $MINENAME

cd ~/java/ncgr/intermine
echo "########## transcriptreferenceupdater $MINENAME"
./transcriptreferenceupdater $MINENAME

cd ~/$MINENAME
echo "########## update genefamily.size $DBNAME ##########"
psql $DBNAME -c "UPDATE genefamily SET intermine_size = (SELECT count(*) FROM gene WHERE gene.genefamilyid=genefamily.id)"

## remove triggers
psql $DBNAME -f dbmodel/build/resources/main/remove-update-triggers.sql
