#!/bin/sh
rm -f intermine.log

echo ""
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo "#################################################### LEGUMEMINE INTEGRATE ################################################################"
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo ""

## ontologies and InterPro
./gradlew integrate -Psource=go --stacktrace
./gradlew integrate -Psource=so --stacktrace
./gradlew integrate -Psource=plant-ontology --stacktrace
./gradlew integrate -Psource=plant-trait-ontology --stacktrace
./gradlew integrate -Psource=interpro --stacktrace
./gradlew integrate -Psource=interpro-go --stacktrace

## LIS gene families
./gradlew integrate -Psource=lis.fam1-genefamily --stacktrace

###########
## phavu ##
###########

./gradlew integrate -Psource=phavu-about --stacktrace

## phavu.G19833.gnm1
./gradlew integrate -Psource=phavu.G19833.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-info-annot --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-mrna-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1-expression --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm1.ann1.syn1-synteny --stacktrace

## phavu.G19833.gnm2
./gradlew integrate -Psource=phavu.G19833.gnm2-chromosome-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1-gff --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1-info-annot --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1-mrna-fasta --stacktrace
./gradlew integrate -Psource=phavu.G19833.gnm2.ann1.syn1-synteny --stacktrace

## phavu.UI111.gnm1
./gradlew integrate -Psource=phavu.UI111.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=phavu.UI111.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=phavu.UI111.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=phavu.UI111.gnm1.ann1-info-annot --stacktrace
./gradlew integrate -Psource=phavu.UI111.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=phavu.UI111.gnm1.ann1-mrna-fasta --stacktrace

###########
## cicar ##
###########

./gradlew integrate -Psource=cicar-about --stacktrace

## cicar.CDCFrontier.gnm1
./gradlew integrate -Psource=cicar.CDCFrontier.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=cicar.CDCFrontier.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=cicar.CDCFrontier.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=cicar.CDCFrontier.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=cicar.CDCFrontier.gnm1.ann1.syn1-synteny --stacktrace

## cicar.ICC4958.gnm2
./gradlew integrate -Psource=cicar.ICC4958.gnm2-chromosome-fasta --stacktrace
./gradlew integrate -Psource=cicar.ICC4958.gnm2.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=cicar.ICC4958.gnm2.ann1-gff --stacktrace
./gradlew integrate -Psource=cicar.ICC4958.gnm2.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=cicar.ICC4958.gnm2.ann1.syn1-synteny --stacktrace
./gradlew integrate -Psource=cicar.ICC4958.gnm2.ann1-expression --stacktrace

###########
## vigun ##
###########

./gradlew integrate -Psource=vigun-about --stacktrace

## vigun.IT97K-499-35
./gradlew integrate -Psource=vigun.IT97K-499-35.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=vigun.IT97K-499-35.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=vigun.IT97K-499-35.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=vigun.IT97K-499-35.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=vigun.IT97K-499-35.gnm1.ann1-transcript-fasta --stacktrace
./gradlew integrate -Psource=vigun.IT97K-499-35.gnm1.syn1-synteny --stacktrace
./gradlew integrate -Psource=vigun.IT97K-499-35.gnm1.ann1-expression --stacktrace

## vigun.CB5_2
./gradlew integrate -Psource=vigun.CB5_2.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=vigun.CB5_2.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=vigun.CB5_2.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=vigun.CB5_2.gnm1.ann1-protein-fasta --stacktrace

## vigun.Sanzi
./gradlew integrate -Psource=vigun.Sanzi.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=vigun.Sanzi.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=vigun.Sanzi.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=vigun.Sanzi.gnm1.ann1-protein-fasta --stacktrace

## vigun.Suvita2
./gradlew integrate -Psource=vigun.Suvita2.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=vigun.Suvita2.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=vigun.Suvita2.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=vigun.Suvita2.gnm1.ann1-protein-fasta --stacktrace

## vigun.TZ30
./gradlew integrate -Psource=vigun.TZ30.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=vigun.TZ30.gnm1.ann2-gff --stacktrace
./gradlew integrate -Psource=vigun.TZ30.gnm1.ann2-cds-fasta --stacktrace
./gradlew integrate -Psource=vigun.TZ30.gnm1.ann2-protein-fasta --stacktrace

## vigun.UCR779
./gradlew integrate -Psource=vigun.UCR779.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=vigun.UCR779.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=vigun.UCR779.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=vigun.UCR779.gnm1.ann1-protein-fasta --stacktrace

## vigun.Xiabao_II
./gradlew integrate -Psource=vigun.Xiabao_II.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=vigun.Xiabao_II.gnm1.ann1-gff --stacktrace

## vigun.ZN016
./gradlew integrate -Psource=vigun.ZN016.gnm1-chromosome-fasta
./gradlew integrate -Psource=vigun.ZN016.gnm1.ann2-gff
./gradlew integrate -Psource=vigun.ZN016.gnm1.ann2-cds-fasta
./gradlew integrate -Psource=vigun.ZN016.gnm1.ann2-protein-fasta

###########
## lupal ##
###########

./gradlew integrate -Psource=lupal-about

## lupal.Amiga
./gradlew integrate -Psource=lupal.Amiga.gnm1-chromosome-fasta
./gradlew integrate -Psource=lupal.Amiga.gnm1.ann0-gff
./gradlew integrate -Psource=lupal.Amiga.gnm1.ann0-cds-fasta
./gradlew integrate -Psource=lupal.Amiga.gnm1.ann0-mrna-fasta
./gradlew integrate -Psource=lupal.Amiga.gnm1.ann0-protein-fasta

###########
## lupan ##
###########

./gradlew integrate -Psource=lupan-about

## lupan.Tanjil
./gradlew integrate -Psource=lupan.Tanjil.gnm1-chromosome-fasta
./gradlew integrate -Psource=lupan.Tanjil.gnm1.ann1-gff
./gradlew integrate -Psource=lupan.Tanjil.gnm1.ann1-cds-fasta
./gradlew integrate -Psource=lupan.Tanjil.gnm1.ann1-protein-fasta
./gradlew integrate -Psource=lupan.Tanjil.gnm1.ann1.syn1-synteny

###########
## medtr ##
###########

./gradlew integrate -Psource=medtr-about --stacktrace

## medtr.A17_HM341.gnm4
./gradlew integrate -Psource=medtr.A17_HM341.gnm4-chromosome-fasta --stacktrace
./gradlew integrate -Psource=medtr.A17_HM341.gnm4.ann2-gff --stacktrace
./gradlew integrate -Psource=medtr.A17_HM341.gnm4.ann2-cds-fasta --stacktrace
./gradlew integrate -Psource=medtr.A17_HM341.gnm4.ann2-protein-fasta --stacktrace

## medtr.R108_HM340.gnm1
./gradlew integrate -Psource=medtr.R108_HM340.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=medtr.R108_HM340.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=medtr.R108_HM340.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=medtr.R108_HM340.gnm1.ann1-protein-fasta --stacktrace

###########
## glyma ##
###########

./gradlew integrate -Psource=glyma-about --stacktrace
./gradlew integrate -Psource=glyma-phenotypes --stacktrace

## glyma.mixed
./gradlew integrate -Psource=mixed.gwas.1W14-gwas --stacktrace

## glyma.Wm82.gnm2
./gradlew integrate -Psource=glyma.Wm82.gnm2-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-info-annot --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-gff --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-mrna-fasta --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1-expression --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.mrk1-gff --stacktrace
./gradlew integrate -Psource=glyma.Wm82.gnm2.ann1.syn1-synteny --stacktrace

## glyma.Lee.gnm1
./gradlew integrate -Psource=glyma.Lee.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-info-annot --stacktrace
./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=glyma.Lee.gnm1.ann1-mrna-fasta --stacktrace

## glyma.Zh13.gnm1
./gradlew integrate -Psource=glyma.Zh13.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyma.Zh13.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=glyma.Zh13.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyma.Zh13.gnm1.ann1-protein-fasta --stacktrace

###########
## glyso ##
###########

./gradlew integrate -Psource=glyso-about --stacktrace

## glyso.PI483463.gnm1
./gradlew integrate -Psource=glyso.PI483463.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-info-annot --stacktrace
./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=glyso.PI483463.gnm1.ann1-mrna-fasta --stacktrace

## glyso.W05.gnm1
./gradlew integrate -Psource=glyso.W05.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=glyso.W05.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=glyso.W05.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=glyso.W05.gnm1.ann1-protein-fasta --stacktrace
