#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "########################## ${LP}EXPRESSION${NC} ###########################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=ICPL87119.gnm1.ann1.expr.4H6Z
./gradlew integrate --stacktrace -Psource=ICC4958.gnm2.ann1.expr.4Y7B
./gradlew integrate --stacktrace -Psource=Wm82.gnm2.ann1.expr.G7ZY
./gradlew integrate --stacktrace -Psource=A17_HM341.gnm4.ann2.expr.RLZY
./gradlew integrate --stacktrace -Psource=G19833.gnm1.ann1.expr.4ZDQ
./gradlew integrate --stacktrace -Psource=IT97K-499-35.gnm1.ann1.expr.BWH5
