#!/bin/bash
## Run single gradlew integrate jobs on each source given below.

NC='\033[0m'
LP='\033[1;35m'

for SOURCE in go so interpro interpro-go pfam-term panther-term plant-ontology plant-trait-ontology legume.genefam.fam1.M65K legume.genefam.fam1.M65K.trees_ML_rooted
do
    echo "####"
    echo -e "#### ${LP}${SOURCE}${NC}"
    echo "####"
    ./gradlew integrate --stacktrace -Psource=$SOURCE
done

