#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'
echo -e "#################################################################"
echo -e "########################## ${LP}DESCRIPTIONS${NC} #########################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=Aeschynomene-evenia-description
./gradlew integrate --stacktrace -Psource=Arachis-duranensis-description
./gradlew integrate --stacktrace -Psource=Arachis-hypogaea-description
./gradlew integrate --stacktrace -Psource=Arachis-ipaensis-description
./gradlew integrate --stacktrace -Psource=Cajanus-cajan-description
./gradlew integrate --stacktrace -Psource=Chamaecrista-fasciculata-description
./gradlew integrate --stacktrace -Psource=Cicer-arietinum-description
./gradlew integrate --stacktrace -Psource=Glycine-cyrtoloba-description
./gradlew integrate --stacktrace -Psource=Glycine-D3-tomentella-description
./gradlew integrate --stacktrace -Psource=Glycine-dolichocarpa-description
./gradlew integrate --stacktrace -Psource=Glycine-falcata-description
./gradlew integrate --stacktrace -Psource=Glycine-max-description
./gradlew integrate --stacktrace -Psource=Glycine-soja-description
./gradlew integrate --stacktrace -Psource=Glycine-stenophita-description
./gradlew integrate --stacktrace -Psource=Glycine-syndetika-description
./gradlew integrate --stacktrace -Psource=Lotus-japonicus-description
./gradlew integrate --stacktrace -Psource=Lupinus-albus-description
./gradlew integrate --stacktrace -Psource=Lupinus-angustifolius-description
./gradlew integrate --stacktrace -Psource=Medicago-sativa-description
./gradlew integrate --stacktrace -Psource=Medicago-truncatula-description
./gradlew integrate --stacktrace -Psource=Phaseolus-acutifolius-description
./gradlew integrate --stacktrace -Psource=Phaseolus-lunatus-description
./gradlew integrate --stacktrace -Psource=Phaseolus-vulgaris-description
./gradlew integrate --stacktrace -Psource=Pisum-sativum-description
./gradlew integrate --stacktrace -Psource=Trifolium-pratense-description
./gradlew integrate --stacktrace -Psource=Vigna-angularis-description
./gradlew integrate --stacktrace -Psource=Vigna-radiata-description
./gradlew integrate --stacktrace -Psource=Vigna-unguiculata-description
