#!/bin/sh

## clear the logs (quietly)
rm -f intermine*.log

## echo a big marker so we can see when this run started in the scroll
echo "##################################################################################################"
echo "##################################### postprocess ################################################"
echo "##################################################################################################"

# ## legfed
# ./gradlew postprocess -Pprocess=legfed-create-gene-flanking-regions --stacktrace
# ./gradlew postprocess -Pprocess=legfed-create-intron-features --stacktrace
# ./gradlew postprocess -Pprocess=legfed-create-exon-gene-references --stacktrace
# ./gradlew postprocess -Pprocess=legfed-create-protein-gene-references --stacktrace
# ./gradlew postprocess -Pprocess=legfed-create-supercontig-flanking-regions --stacktrace
# ./gradlew postprocess -Pprocess=legfed-create-go-annotations --stacktrace
# ./gradlew postprocess -Pprocess=legfed-populate-interpro-data --stacktrace
# ./gradlew postprocess -Pprocess=legfed-populate-publications --stacktrace

# ## more features
# ./gradlew postprocess -Pprocess=create-intergenic-region-features --stacktrace

## create various references and collections and sequences
./gradlew postprocess -Pprocess=populate-child-features --stacktrace
./gradlew postprocess -Pprocess=create-references --stacktrace
./gradlew postprocess -Pprocess=create-chromosome-locations-and-lengths --stacktrace
./gradlew postprocess -Pprocess=transfer-sequences --stacktrace

## views and indexes, after all data is set
./gradlew postprocess -Pprocess=create-location-overlap-index --stacktrace
./gradlew postprocess -Pprocess=create-overlap-view --stacktrace

## these must be run after any data is changed
./gradlew postprocess -Pprocess=create-attribute-indexes --stacktrace
./gradlew postprocess -Pprocess=summarise-objectstore --stacktrace

## these require Solr server
./gradlew postprocess -Pprocess=create-autocomplete-index --stacktrace
./gradlew postprocess -Pprocess=create-search-index --stacktrace
