#!/bin/sh
rm -f validate-synteny.md
touch validate-synteny.md
for COLLECTION in Arachis/duranensis/synteny/V14167.gnm1.syn.qmkW \
                      Arachis/ipaensis/synteny/K30076.gnm1.syn.S8s4 \
                      Cajanus/cajan/synteny/ICPL87119.gnm1.syn.Nkx0 \
                      Cicer/arietinum/synteny/CDCFrontier.gnm1.syn.7Bqh \
                      Cicer/arietinum/synteny/ICC4958.gnm2.syn.PdvJ \
                      Glycine/max/synteny/Wm82.gnm2.syn.HXNY \
                      Lotus/japonicus/synteny/MG20.gnm3.syn.0ZB0 \
                      Lupinus/angustifolius/synteny/Tanjil.gnm1.syn.TwnC \
                      Phaseolus/vulgaris/synteny/G19833.gnm1.syn.xQ7F \
                      Phaseolus/vulgaris/synteny/G19833.gnm2.syn.DVDW \
                      Trifolium/pratense/synteny/MilvusB.gnm2.syn.dXVX \
                      Vigna/angularis/synteny/Gyeongwon.gnm3.syn.wCFF \
                      Vigna/radiata/synteny/VC1973A.gnm6.syn.mcwy \
                      Vigna/unguiculata/synteny/IT97K-499-35.gnm1.syn.W3NY
do
    validate-synteny-collection /data/v2/$COLLECTION >> validate-synteny.md
done




