#!/bin/sh
rm -f validate-expression.md
touch validate-expression.md
for COLLECTION in Cajanus/cajan/expression/ICPL87119.gnm1.ann1.expr.4H6Z \
                      Cicer/arietinum/expression/ICC4958.gnm2.ann1.expr.4Y7B \
                      Glycine/max/expression/Wm82.gnm2.ann1.expr.G7ZY \
                      Medicago/truncatula/expression/A17_HM341.gnm4.ann2.expr.RLZY \
                      Phaseolus/vulgaris/expression/G19833.gnm1.ann1.expr.4ZDQ \
                      Vigna/unguiculata/expression/IT97K-499-35.gnm1.ann1.expr.BWH5
do
    validate-expression-collection /data/v2/$COLLECTION >> validate-expression.md
done





