#!/bin/sh
echo "********** legumemine/postprocess **********"
ant clean

# the full Monty
ant -v

# add features
#ant -Daction=create-intron-features
#ant -Daction=create-intergenic-region-features
#ant -Daction=create-gene-flanking-features

# create various references and collections
#ant -Daction=populate-located-features
#ant -Daction=populate-child-features
#ant -Daction=create-references
#ant -Daction=create-chromosome-locations-and-lengths
#ant -Daction=transfer-sequences

# views and indexes, after all data is set
#ant -Daction=create-location-overlap-index
#ant -Daction=create-overlap-view
#ant -Daction=create-attribute-indexes
#ant -Daction=summarise-objectstore
#ant -Daction=create-autocomplete-index
#ant -Daction=create-search-index
