#!/bin/sh
echo "********** legumemine/integrate **********"
ant clean

## ontologies
#ant -v -Dsource=so,go,to,po

## LIS chado loaders (includes peanut genomics)
#ant -v -Dsource=lis-genomics,lis-genetics,lis-featureprop,lis-reactome-file,lis-genefamilies,lis-homology

## PeanutBase chado loaders (genetics)
#ant -v -Dsource=peanutbase-genetics,peanutbase-featureprop

## restore the full chado load
#pg_restore -d legumemine /home/shokin/dumps/legumemine.chado.dat

############################################################################################################################
# ALL of the chado data loading must be DONE and BACKED UP before continuing, because identifiers are changed by SQL below #
############################################################################################################################

## post-chado organism attribute updates, no change to existing chado data
#psql legumemine -f ../dbmodel/build/model/add-update-triggers.sql
#psql legumemine -f ../sql/cleanup-chado-bugs.sql
#psql legumemine -f ../sql/update-organism-genus-species.sql
#psql legumemine -f ../sql/update-organism-descriptions.sql
#psql legumemine -f ../sql/update-identifiers.sql
#psql legumemine -f ../dbmodel/build/model/remove-update-triggers.sql

## germplasm files (organism varieties, with descriptions)
#ant -v -Dsource=cowpea-germplasms

## QTL files
#ant -v -Dsource=cowpea-qtl-file,soybase-qtl-file

## QTL ontology terms
#ant -v -Dsource=bean-qtl-trait-ontology,cowpea-qtl-trait-ontology,soybase-qtl-trait-ontology

## QTLs - markers
#ant -v -Dsource=cowpea-marker-qtl-file,soybase-marker-qtl-file

## SNPs
#ant -v -Dsource=cowpea-snpmarkers

## SNP positions
#ant -v -Dsource=cowpea-snppositions

## linkage groups
#ant -v -Dsource=soybase-linkagegroup-file,cowpea-linkagegroup-file

## linkage groups - markers
#ant -v -Dsource=soybase-marker-linkagegroup-file,cowpea-marker-linkagegroup-file

## markers from GFF
#ant -v -Dsource=peanut-geneticmarker-gff

## marker chromosome positions
#ant -v -Dsource=soybase-marker-chromosome-file

## Expression
#ant -v -Dsource=bean-expression,chickpea-expression,peanut-expression,soybean-expression,pigeonpea-expression,cowpea-expression

## update the genus and species for the germplasms we added, don't touch the descriptions!
#psql legumemine -f ../dbmodel/build/model/add-update-triggers.sql
#psql legumemine -f ../sql/update-organism-genus-species.sql
#psql legumemine -f ../dbmodel/build/model/remove-update-triggers.sql
